name: CI - Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Run tests (Python 3.11)
    runs-on: ubuntu-latest

    env:
      # Dummy env vars so tests relying on configuration don't fail
      TELEGRAM_BOT_TOKEN: dummy-token
      OPENAI_API_KEY: dummy-api-key
      HOMEBOX_URL: http://localhost
      HOMEBOX_USER: dummy
      HOMEBOX_PASSWORD: dummy
      HOMEBOX_TOKEN: dummy
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: src

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Prepare runtime directories
        run: |
          mkdir -p logs data temp

      - name: Check i18n key sync
        run: |
          python scripts/check_i18n.py

      - name: Run tests with coverage
        run: |
          python -m pytest tests/ --strict-markers --cov=src \
            --cov-report=term-missing --cov-report=xml --cov-report=html -v

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage HTML artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-html
          path: htmlcov

      - name: Upload coverage XML artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-xml
          path: coverage.xml


